
development:
  adapter: postgresql
  encoding: unicode
  database: mnemonic_development
  pool: 5
  username: railsapp
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: mnemonic_test
  pool: 5
  username: railsapp
  password:
